###################### Filebeat Configuration Example #########################

# This file is an example configuration file highlighting only the most common
# options. The filebeat.reference.yml file from the same directory contains all the
# supported options with more comments. You can use it as a reference.
#
# You can find the full configuration reference here:
# https://www.elastic.co/guide/en/beats/filebeat/7.10/filebeat-reference-yml.html

#=========================== Filebeat inputs =============================

filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /home/cowrie/cowrie/var/log/cowrie/cowrie.json*

setup.template.settings:
  index.number_of_shards: 1

output.logstash:
  enabled: true
  # The Logstash hosts
  hosts: ["localhost:5044"]

# Max number of harvesters that are started in parallel.
# Default is 0 which means unlimited
harvester_limit: 2

# Drop unnecessary fields
processors:
  - drop_fields:
      fields: ["agent", "log", "input", "ecs"]

# Registry data path. If a relative path is used, it is considered relative to the
# data path.
filebeat.registry.path: /home/ubuntu/filebeat-registry
